name: bitcoin_icons
description: This Package provides a comprehensive collection of icons specifically designed for Bitcoin applications.
version: 0.0.4
homepage: https://github.com/aniketambore/bitcoin_icons
repository: https://github.com/aniketambore/bitcoin_icons
license: MIT

environment:
  sdk: '>=2.19.0 <3.0.5'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  fonts:
    - family: BitcoinIcons
      fonts:
        - asset: icons/BitcoinIcons.ttf
